name: 'Apply_TF_Plan'
 
on: workflow_dispatch
 
jobs:
  apply-plan:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shelll regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: "./terraform/PRO"
        
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: az_tf_plan.yml
          name: myartifact
          path: "./terraform"
          search_artifacts: true
          
      - name: ls
        run: ls
        working-directory: "./terraform"

      - name: Decompress TF Plan artifact
        run: unzip myartifact.zip
        working-directory: "./terraform"
        
      - name: pwd
        run: pwd
        
      - name: ls
        run: ls
        working-directory: "./terraform"
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.4.6
        
      - name: Terraform Apply
        run: terraform apply plan.tfplan

