name: 'Build_TF_Plan'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  build-plan:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: "./terraform/PRO"
        
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      id: init
      run: terraform init 
      
    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan --out=plan.tfplan
        
    - name: Compress TF Plan artifact
      run: zip -r myartifact.zip . -i ./*

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: myartifact
        path: "./terraform/PRO/myartifact.zip"
        retention-days: 5
        
    - name: Download Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: myartifact
        path: "./terraform/myartifact.zip"

    - name: Decompress TF Plan artifact
      run: unzip myartifact.zip
